### ISSUE TITLE
Using Pkarr instead of mainline with special Salt(s) and encoding.

### ISSUE THREAD

**Issue by Nuhvi** [SteveFarroll/mosaic-spec#15]
Hey, just noticed this project, and I like the plans to use mainline, however, I think you should consider using [Pkarr](pkarr.org) itself, since it is designed to do the same thing you are trying to do, but not just you, it is trying to offer users what renting a domain offers them.

Whoever succeeds at putting a key management app in users hand, that actually allows them to keep their keys long term, should not limit the benefit of this massive feat to one project, instead it should allow users to advertise _any_ protocol, just like they can with TXT or SVCB records for example.

Moreover Pkarr offers relays and resolvers, maintained by everyone who supports pkarr, and that helps with reliability, latency, and browser support.

Pkarr also is trying to tackle TLS for Pkarr keys, and this is a problem that honestly doesn't need to be fixed multiple times, so why not collaborate to do it just once and we all benefit from? 

One minor detail that showcases that Pkarr thought this through, is `seq` number, where this spec says it should start with `1` and increases monotonically, whereas, Pkarr chooses to make it a Timestamp with enough resolution, because this way you can create the most recent packet from any device (although admittedly if you are not sure you know the most recent packet so far, you risk losing data if you don't read before writing). 

Caching logic, TTL, etc. are also all stuff that can be controlled easily with DNS semantics, and DNS encoding is very good and performant, and I think a 1000 bytes are all a user will ever need just to point to where their actual storage is.

We have a long history of using DNS records to point to endpoints, and in fact that is the most appropriate format to do that, so it should be easy to explain to most developers.

I would love more eyes on Pkarr especially on the still nascent TLS work, so I this should be beneficial for everyone.

Thanks for considering, and thanks for trusting our Mainline implementation either-way.

#### Server Bootstrap

A server with public key `m7iszmgdf8oxbsgrnh4wzooefzq3y6chmp11uf5zs1yji4wpxieo` can advertise their endpoints like this:

```zone
@                     30    IN      A       203.0.113.1
@                     30    IN      AAAA    2001::130F:09C0:876A:130B
_ws.mosaic.           30    IN      SVCB    .       (alpn="h3" port="5198")
_onion.mosaic.        30    IN      SVCB    myserverlk23lkjsefo8u.onion
_webtransport.mosaic. 30    IN      SVCB    mosaic.example   (port="555")
```

The last 3 records are [service binding](https://www.rfc-editor.org/rfc/rfc9460#name-dns-server-behavior) records and the first two are pointing the target `.` to IPv4 and IPv6 IPs. 

#### User Bootstrap
A user with public key `o4dksfbqk85ogzdb5osziw6befigbuxmuxkuxq8434q89uj56uyy` can advertise their servers like this: 

```zone
_outbox.mosaic.       30      IN      SVCB    m7iszmgdf8oxbsgrnh4wzooefzq3y6chmp11uf5zs1yji4wpxieo.
_inbox.mosaic.        30      IN      SVCB    m7iszmgdf8oxbsgrnh4wzooefzq3y6chmp11uf5zs1yji4wpxieo.
_encryption.mosaic.   30      IN      SVCB    m7iszmgdf8oxbsgrnh4wzooefzq3y6chmp11uf5zs1yji4wpxieo.
```

The user can easily (among other things) point to their mosaic servers, and the server's public key is just the TLD.

In fact because how DNS packet encoding works if the user uses only one server for all three functions, the server's public key will be encoded once and then compressed for the next two records, so will `.mosaic` be replaced with a pointer to its first occurrence.

cc: @mikedilger

**Comment by mikedilger** [comment]
And I think pkarr makes sense for what you are doing... for giving people a domain that they are sovereign over, and for browsers to interact with that domain.

But for mosaic, putting another layer (a pkarr dns service) in the path between the mosaic client and the DHT doesn't add any value to mosaic, but it does add another point of failure.  Also, the mosaic records in DNS wouldn't be useful to anybody outside of mosaic itself.  So I don't see it adding any value to anything.

Also, the user can use the same keypair and key management apps etc as they do with pkarr.  Mosaic is using salts so that the same key won't collide with your DHT records.

We haven't worked out any of the TLS things yet.  That is all "in principle" and if we can't do it technically, we will fallback to something else until we can.

BTW: I love DNS and have been editing bind zone files since the 1990s (starting on a sun3 keyboard even), always remembering that damn trailing dot. So I'm not a spring chicken here and have no animus towards DNS.

**Comment by Nuhvi** [comment]
I like your taste in protocol design, so I wish you best of luck. 

Fwiw, we will keep developing Pkarr and Pubky-core including infrastructure, but more importantly UX for key management. Maybe by the time you decide to commit, you might find that we built enough tools for users, for interop to be worth it.

**Comment by SteveFarroll** [comment]
> Hey, just noticed this project, and I like the plans to use mainline

Hello, and thanks for that crate.

> One minor detail that showcases that Pkarr thought this through, is seq number, where this spec says it should start with 1 and increases monotonically, whereas, Pkarr chooses to make it a Timestamp with enough resolution, because this way you can create the most recent packet from any device (although admittedly if you are not sure you know the most recent packet so far, you risk losing data if you don't read before writing).

I don't expect people to write often or from multiple places as this has to be done with the secure master key, and yes they have to read before they write.  Currently I'm looping through all the responses and keeping the one with the highest number.  While it is theoretically possible to not see the latest write, in our circumstance it is very unlikely.

> Maybe by the time you decide to commit, you might find that we built enough tools for users, for interop to be worth it.

That is totally possible. I don't think mosaic is something that will be built out rapidly, it is more of a way to organize the ideas Mike had for a successor to nostr in a more concrete fashion... and to nudge him.
